name: PR Preview 2 Build

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: read

jobs:
  preview:
    uses: simoneonofri/pr-preview-2/.github/workflows/build.yml@v0.1.0-alpha.1
    with:
      toolchain: respec
      source: index.html
